### ISSUE TITLE
Problem during a push into github.

### ISSUE THREAD

**Issue by MassimoBelfioreCode** [UNICT-Quality-Development/qd-starter-pack#22]
Ho riscontrato un problema durante il push di un file su github.
Il problema è il seguente: Dopo aver fatto git push -u origin 'nomenuovobranch', è partita l'autenticazione da terminale richiedendomi sia username per 'https://github.com' che password, e ho ottenuto come errore :"remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead". E poi ancora "fatal: Authentication failed for 'https://github.com/MassimoBelfioreCode/qd-starter-pack.git/' ". Sono sicuro di aver inserito username e password del mio account github correttamente ma non mi fa pushare. L'obbiettivo era quello di creare una pull request. Qualcuno potrebbe aiutarmi dicendomi come risolvere?
Scusatemi, sto ancora imparando molto sull'uso corretto di github.

**Comment by MassimoBelfioreCode** [comment]
Ho provato purtroppo a riclonare la repository ma adesso ho riscontrato questo errore:
ERROR: Permission to UNICT-Quality-Development/qd-starter-pack.git denied to MassimoBelfioreCode.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Non saprei cosa fare. Cerco aiuto per risolvere

**Comment by Helias** [comment]
@MassimoBelfioreCode Perchè al posto di USERNAME metti "UNICT-Quality-Development", invece devi mettere il tuo USERNAME di GitHub, se hai forkato la repository, la tua repository si trova su

git@github.com/MassimoBelfioreCode/qd-starter-pack.git

NON in

git@github.com/UNICT-Quality-Development/qd-starter-pack.git
